ALTER DATABASE WideWorldImportersDW SET COMPATIBILITY_LEVEL = 150		-- SQL Server 2019

-- 29,620,736 rows
SELECT COUNT(*) FROM Fact.OrderHistoryExtended

SELECT COUNT(DISTINCT [WWI Order ID]) AS ExactCount FROM Fact.OrderHistoryExtended
 OPTION (USE HINT('DISALLOW_BATCH_MODE'), RECOMPILE)

SELECT APPROX_COUNT_DISTINCT([WWI Order ID]) AS ApproxCount FROM Fact.OrderHistoryExtended
 OPTION (USE HINT('DISALLOW_BATCH_MODE'), RECOMPILE)
