USE Library
GO

DROP SECURITY POLICY IF EXISTS BranchManagerPolicy
DROP FUNCTION IF EXISTS BranchManagerPredicate
DROP PROCEDURE IF EXISTS GetBooksCowrittenByAuthor
DROP VIEW IF EXISTS vwRandomNumber
DROP FUNCTION IF EXISTS dbo.GetBioUdf
DROP VIEW IF EXISTS vwBookDetails
DROP TABLE IF EXISTS BookAuthor
DROP TABLE IF EXISTS Book
DROP TABLE IF EXISTS Author

USE master
GO

DROP DATABASE Library
GO
